# Generated by Django 5.2.8 on 2025-11-16 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(max_length=100, verbose_name='Магазин')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('date', models.DateField(verbose_name='Дата перемещения')),
                ('worker', models.CharField(max_length=100, verbose_name='Кладовщик')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp_var_6.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Перемещение',
                'verbose_name_plural': 'Перемещения',
                'ordering': ['-date'],
            },
        ),
    ]
